version: '3.9'
services:
  study-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/nextjs-dashboard # ローカルをコンテナ内にマウント
    # command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 

